### ISSUE TITLE
Grouper error: /usr/local/lib/python2.7/dist-packages/click/core.py:535: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.   return callback(*args, **kwargs)

### ISSUE THREAD

**Issue by lychen83** [COMBINE-lab/grouper#1]
Hello,

I am using Grouper.  Clustering without  annotation from a related species works well. However, when I used a related species, Grouper failed to work.
The config file is:
_conditions:
    - control
    - 35
    - 40
    - 45
samples:
    control:
        - SRR4447140decont-_Trinity_v2.6.5_salmon_mapping
        - SRR4447141decont-_Trinity_v2.6.5_salmon_mapping
        - SRR4447142decont-_Trinity_v2.6.5_salmon_mapping
    35:
        - SRR4447143decont-_Trinity_v2.6.5_salmon_mapping
        - SRR4447144decont-_Trinity_v2.6.5_salmon_mapping
        - SRR4447145decont-_Trinity_v2.6.5_salmon_mapping
    40:
        - SRR4447146decont-_Trinity_v2.6.5_salmon_mapping
        - SRR4447147decont-_Trinity_v2.6.5_salmon_mapping
        - SRR4447148decont-_Trinity_v2.6.5_salmon_mapping
    45:
        - SRR4447149decont-_Trinity_v2.6.5_salmon_mapping
        - SRR4447150decont-_Trinity_v2.6.5_salmon_mapping
        - SRR4447151decont-_Trinity_v2.6.5_salmon_mapping
Fasta:
    - deconta-_Trinity_v2.6.5.fasta
    - Egrandis_297_v2.0.transcript.fa
outdir: grouper_salmon_results_

I have installed biogrouper using pip, mcl, junto, and set to my environment. 
However, I got error:

_2018-03-10 17:07:42 eeb-bigsmith root[25754] INFO Done running BLAST using 11 threads
2018-03-10 17:07:42 eeb-bigsmith root[25754] INFO Processing the BLAST output.
2018-03-10 17:07:42 eeb-bigsmith root[25754] INFO Getting txp lengths from: SRR4447140decont-_Trinity_v2.6.5_salmon_mapping/quant.sf
/usr/local/lib/python2.7/dist-packages/click/core.py:535: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  return callback(*args, **kwargs)
619096 edges checkedTraceback (most recent call last):
  File "/usr/local/bin/Grouper", line 238, in <module>
    processQuant()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/Grouper", line 170, in processQuant
    iterLabel.run(keys, finalLabelFile, juntoConfigFile, filtNetFile, outdir)
  File "/usr/local/lib/python2.7/dist-packages/grouper/iterLabel.py", line 131, in run
    orgGraph[edge[0]].add((edge[1], float(edge[2])))
ValueError: could not convert string to float: {'capacity': 1.1}_

I got following output in output dir (some files attached):
_AS  AS.TSdb  junto.config  log.txt  mag.filt.net  mag.net  seed.labels.txt  seed.txt  TS  TS.ASdb_

Could you kindly give me suggestion to resolve this problem?
Thank you so much.

Best wishes,
Chen
[grouper_salmon_results_klaxiflora.zip](https://github.com/COMBINE-lab/grouper/files/1800020/grouper_salmon_results_klaxiflora.zip)

**Comment by lychen83** [comment]
Thanks to Laraib, I resolved the problem. 

As Laraib has suggested, the error I mentioned is due to networkx.  This version of Grouper requires network 1.11. If install Gouper using pip, it will automatically install networkx 2.1.

To uninstall 2.1 and install 1.11 using commands:
1  _pip uninstall networkx_
2  download netowrkx 1.11:
_wget https://pypi.python.org/packages/f1/8e/f6f345ed7b228d080e338eac5a6bcce2260390468ae9130dcb67096f59c4/networkx-1.1.tar.gz#md5=f72e260447711ca0fd7b1b1de5a2396d ./_
3  _pip install networkx-1.11.tar.gz_ 

------
I also got error: _Error: Could not find or load main class upenn.junto.app.JuntoConfigRunner_
This is because junto was not correctly installed.

4  After decompress junto, set to environment (my example):
_JUNTO_DIR=/home/clingyun/CHEN/biosofts/junto-master/
export PATH="$PATH:$JUNTO_DIR/bin"_

5   Then install junto in folder examples/simple:
_bin/build update compile
bin/build assembly_

6   Test if Junto work:
_junto config simple_config_

On my workstation, java 1.6 not work with Junto.  java version "1.8.0_144"---Java(TM) SE Runtime Environment (build 1.8.0_144-b01) work with Junto, as well as Grouper

Chen Lingyun
