### ISSUE TITLE
networkx error with mincut: True

### ISSUE THREAD

**Issue by jfordonez** [COMBINE-lab/grouper#2]
Hello! I encountered this error when I set mincut to True. I have networkx1.1 installed. Kindly advise. Thank you!

2018-10-08 18:01:24 sandfishtrace root[12250] INFO Done reading files for filtering.
16 edges checkedTraceback (most recent call last):
  File "/home/sandfishtrace/src/anaconda2/bin/Grouper", line 238, in <module>
    processQuant()
  File "/home/sandfishtrace/src/anaconda2/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/sandfishtrace/src/anaconda2/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/sandfishtrace/src/anaconda2/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sandfishtrace/src/anaconda2/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/sandfishtrace/src/anaconda2/bin/Grouper", line 134, in processQuant
    eqnet.filterGraph(conditionDict, orphanNetFile, filtNetFile, auxDir, mincut)
  File "/home/sandfishtrace/src/anaconda2/lib/python2.7/site-packages/grouper/eqnet.py", line 286, in filterGraph
    value, partition =  nx.minimum_cut(s, x, y)
AttributeError: 'module' object has no attribute 'minimum_cut'

Juny O.

**Comment by laraib85** [comment]
Hi,

Grouper requires networkx version 1.11. Updating the library should fix this issue. You can also download the docker image for Grouper (docker pull combinelab/grouper) to handle all the library requirements.

-Laraib
