### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by manuelsmendoza** [COMBINE-lab/grouper#3]
Hi!

I'm trying to use Grouper to clusterized an assembly done with Trinity. I've create the config file like that:
```
conditions:
- Control
samples:
Control:
- salmon_quant
outdir: grouper
orphan: True
mincut: True
threads: 24
```

But I'm not eable to run Groupe... And I don't understand the error:
```
Traceback (most recent call last):
  File "/mnt/netapp1/Store_uvibgmsm/software/grouper/bin/Grouper", line 238, in <module>
    processQuant()
  File "/mnt/netapp1/Store_uvibgmsm/software/grouper/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/netapp1/Store_uvibgmsm/software/grouper/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/mnt/netapp1/Store_uvibgmsm/software/grouper/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/netapp1/Store_uvibgmsm/software/grouper/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/mnt/netapp1/Store_uvibgmsm/software/grouper/bin/Grouper", line 87, in processQuant
    samples = cfg['samples'][c]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

NOTE:
I'm assembling a transcriptome of reference for a non-model species (without genome) using a single high-depth library.

**Comment by laraib85** [comment]
Hi,

Thank you for using Grouper and I apologize for the delayed response. The error you get is because of the yaml file format. There needs to be a space before all lines under samples for yaml to detect them properly. Try using this:

```
conditions:
    - Control
samples:
    Control:
         - salmon_quant
outdir: grouper
orphan: True
mincut: True
threads: 24
```

**Comment by manuelsmendoza** [comment]
Nice! It's worked!!
