### ISSUE TITLE
ERRO: AttributeError: 'Graph' object has no attribute 'edges_iter'

### ISSUE THREAD

**Issue by manuelsmendoza** [COMBINE-lab/grouper#9]
Hi all,

I'm trying to use Grouper to cluster a transcriptome assembled *de novo* for differential gene expression analysis. 

Firstly of all, I have assembled the transcriptome using Trinity, after assembled I've removed misassembled transcripts using TransRate. Now I wanna remove redundancy using Grouper, in order to do that, I run salmon (as following) and finally Grouper. In the end, I'd an error which I don't understand... What has happened?      

All information below (installing and running configuration).

```bash
# Creating working environment
$ conda create --yes --name clustering_env
$ conda install --yes --name clustering_env --channel bioconda salmon 
$ conda install --yes --name clustering_env --channel lmfaber biogrouper
$ conda activate clustering_env

# Running salmon 
$ salmon index \
>   --threads 40 \
>   --transcripts /path/transcriptome.fasta \
>   --index /path/index 

$ salmon quant \
>   --threads 40 \
>   --libType A \
>   --index /path/index \
>   --geneMap /path/transcriptome.gtm \
>   --mates1 /path/reads_1.fq.gz \
>   --mates2 /path/reads_2.fq.gz \
>   --output /path/output_quant \
>   --seqBias \
>   --gcBias \
>   --validateMappings \
>   --recoverOrphans \
>   --dumpEq \
>   --writeOrphanLinks

# Running grouper ERROR
$ Grouper --config config.yaml
2019-12-20 15:22:16 c6601 root[32028] INFO Building multiple alignment graph
2019-12-20 15:22:16 c6601 root[32028] INFO quant file: EhuHCD1S164_quant/quant.sf; eq file: EhuHCD1S164_quant/aux_info/eq_classes.txt; # tran = 45592; # eq = 136874
2019-12-20 15:22:19 c6601 root[32028] INFO quant file: EhuHCD1S176_quant/quant.sf; eq file: EhuHCD1S176_quant/aux_info/eq_classes.txt; # tran = 45592; # eq = 146098
2019-12-20 15:22:22 c6601 root[32028] INFO quant file: EhuHCD1S193_quant/quant.sf; eq file: EhuHCD1S193_quant/aux_info/eq_classes.txt; # tran = 45592; # eq = 141468
2019-12-20 15:22:25 c6601 root[32028] INFO quant file: EhuHCD2S168_quant/quant.sf; eq file: EhuHCD2S168_quant/aux_info/eq_classes.txt; # tran = 45592; # eq = 137441
2019-12-20 15:22:27 c6601 root[32028] INFO quant file: EhuHCD2S170_quant/quant.sf; eq file: EhuHCD2S170_quant/aux_info/eq_classes.txt; # tran = 45592; # eq = 142394
2019-12-20 15:22:30 c6601 root[32028] INFO quant file: EhuHCD2S195_quant/quant.sf; eq file: EhuHCD2S195_quant/aux_info/eq_classes.txt; # tran = 45592; # eq = 139631
2019-12-20 15:22:32 c6601 root[32028] INFO quant file: EhuLCD1S161_quant/quant.sf; eq file: EhuLCD1S161_quant/aux_info/eq_classes.txt; # tran = 45592; # eq = 131267
2019-12-20 15:22:35 c6601 root[32028] INFO quant file: EhuLCD1S173_quant/quant.sf; eq file: EhuLCD1S173_quant/aux_info/eq_classes.txt; # tran = 45592; # eq = 120946
2019-12-20 15:22:37 c6601 root[32028] INFO quant file: EhuLCD1S192_quant/quant.sf; eq file: EhuLCD1S192_quant/aux_info/eq_classes.txt; # tran = 45592; # eq = 127341
2019-12-20 15:22:39 c6601 root[32028] INFO quant file: EhuLCD2S167_quant/quant.sf; eq file: EhuLCD2S167_quant/aux_info/eq_classes.txt; # tran = 45592; # eq = 131371
2019-12-20 15:22:42 c6601 root[32028] INFO quant file: EhuLCD2S179_quant/quant.sf; eq file: EhuLCD2S179_quant/aux_info/eq_classes.txt; # tran = 45592; # eq = 137947
2019-12-20 15:22:44 c6601 root[32028] INFO quant file: EhuLCD2S194_quant/quant.sf; eq file: EhuLCD2S194_quant/aux_info/eq_classes.txt; # tran = 45592; # eq = 129362
2019-12-20 15:22:47 c6601 root[32028] INFO quant file: EhuHCTRS172_quant/quant.sf; eq file: EhuHCTRS172_quant/aux_info/eq_classes.txt; # tran = 45592; # eq = 166015
2019-12-20 15:22:50 c6601 root[32028] INFO quant file: EhuLCTRS171_quant/quant.sf; eq file: EhuLCTRS171_quant/aux_info/eq_classes.txt; # tran = 45592; # eq = 156752
2019-12-20 15:22:55 c6601 root[32028] INFO Adding information from orphans
2019-12-20 15:23:18 c6601 root[32028] INFO Done reading files for adding orphans
2019-12-20 15:33:20 c6601 root[32028] INFO Added 8033 orphan link edges
2019-12-20 15:33:21 c6601 root[32028] INFO Filtering multiple alignment graph
2019-12-20 15:33:21 c6601 root[32028] INFO conditions = dict_keys(['HCD1', 'HCD2', 'LCD1', 'LCD2', 'TR'])
{0: 'EhuHCD1S164_quant', 1: 'EhuHCD1S176_quant', 2: 'EhuHCD1S193_quant'}
file: EhuHCD1S164_quant/aux_info//eq_classes.txt; # tran = 45592; # eq = 136874
file: EhuHCD1S176_quant/aux_info//eq_classes.txt; # tran = 45592; # eq = 146098
file: EhuHCD1S193_quant/aux_info//eq_classes.txt; # tran = 45592; # eq = 141468
{0: 'EhuHCD2S168_quant', 1: 'EhuHCD2S170_quant', 2: 'EhuHCD2S195_quant'}
file: EhuHCD2S168_quant/aux_info//eq_classes.txt; # tran = 45592; # eq = 137441
file: EhuHCD2S170_quant/aux_info//eq_classes.txt; # tran = 45592; # eq = 142394
file: EhuHCD2S195_quant/aux_info//eq_classes.txt; # tran = 45592; # eq = 139631
{0: 'EhuLCD1S161_quant', 1: 'EhuLCD1S173_quant', 2: 'EhuLCD1S192_quant'}
file: EhuLCD1S161_quant/aux_info//eq_classes.txt; # tran = 45592; # eq = 131267
file: EhuLCD1S173_quant/aux_info//eq_classes.txt; # tran = 45592; # eq = 120946
file: EhuLCD1S192_quant/aux_info//eq_classes.txt; # tran = 45592; # eq = 127341
{0: 'EhuLCD2S167_quant', 1: 'EhuLCD2S179_quant', 2: 'EhuLCD2S194_quant'}
file: EhuLCD2S167_quant/aux_info//eq_classes.txt; # tran = 45592; # eq = 131371
file: EhuLCD2S179_quant/aux_info//eq_classes.txt; # tran = 45592; # eq = 137947
file: EhuLCD2S194_quant/aux_info//eq_classes.txt; # tran = 45592; # eq = 129362
{0: 'EhuHCTRS172_quant', 1: 'EhuLCTRS171_quant'}
file: EhuHCTRS172_quant/aux_info//eq_classes.txt; # tran = 45592; # eq = 166015
file: EhuLCTRS171_quant/aux_info//eq_classes.txt; # tran = 45592; # eq = 156752
2019-12-20 15:33:41 c6601 root[32028] INFO Done reading files for filtering.
0 edges checkedTraceback (most recent call last):
  File "/mnt/netapp1/Store_uvibgmsm/software/miniconda3/envs/clustering_env/bin/Grouper", line 4, in <module>
    __import__('pkg_resources').run_script('biogrouper==0.1.3', 'Grouper')
  File "/mnt/netapp1/Store_uvibgmsm/software/miniconda3/envs/clustering_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/mnt/netapp1/Store_uvibgmsm/software/miniconda3/envs/clustering_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/mnt/netapp1/Store_uvibgmsm/software/miniconda3/envs/clustering_env/lib/python3.7/site-packages/biogrouper-0.1.3-py3.7.egg-info/scripts/Grouper", line 238, in <module>
    processQuant()
  File "/mnt/netapp1/Store_uvibgmsm/software/miniconda3/envs/clustering_env/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/netapp1/Store_uvibgmsm/software/miniconda3/envs/clustering_env/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/mnt/netapp1/Store_uvibgmsm/software/miniconda3/envs/clustering_env/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/netapp1/Store_uvibgmsm/software/miniconda3/envs/clustering_env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/mnt/netapp1/Store_uvibgmsm/software/miniconda3/envs/clustering_env/lib/python3.7/site-packages/biogrouper-0.1.3-py3.7.egg-info/scripts/Grouper", line 134, in processQuant
    eqnet.filterGraph(conditionDict, orphanNetFile, filtNetFile, auxDir, mincut)
  File "/mnt/netapp1/Store_uvibgmsm/software/miniconda3/envs/clustering_env/lib/python3.7/site-packages/grouper/eqnet.py", line 287, in filterGraph
    for e in s.edges_iter(data='capacity'):
AttributeError: 'Graph' object has no attribute 'edges_iter'
```

```yaml
conditions:
        - HCD1
        - HCD2
        - LCD1
        - LCD2
        - TR
samples:
        HCD1:
                - EhuHCD1S164_quant
                - EhuHCD1S176_quant
                - EhuHCD1S193_quant
        HCD2:
                - EhuHCD2S168_quant
                - EhuHCD2S170_quant
                - EhuHCD2S195_quant
        LCD1:
                - EhuLCD1S161_quant
                - EhuLCD1S173_quant
                - EhuLCD1S192_quant
        LCD2:
                - EhuLCD2S167_quant
                - EhuLCD2S179_quant
                - EhuLCD2S194_quant
        TR:
                - EhuHCTRS172_quant
                - EhuLCTRS171_quant
outdir: Ehu_grouper
orphan: True
mincut: True
threads: 40
```

**Comment by laraib85** [comment]
Hi,
This is probably because of the library version for Networkx in python. Make sure you have Networkx v1.11 installed in your conda environment.

**Comment by manuelsmendoza** [comment]
There is a problem with biogrouper in anaconda repo. I tried to install v.1.11 and I've got the following error (biogrouper and networkx v2.3 are coupled)  
 ```bash
$ conda install --yes --name clustering_env --channel conda-forge networkx=1.11
UnsatisfiableError: The following specifications were found to be incompatible with each other:
Package networkx conflicts for:
biogrouper -> networkx=2.3
networkx=1.11
```

**Comment by laraib85** [comment]
Oh, the lmfaber channel biogrouper has this requirement I guess. Try doing "pip install biogrouper" from inside the conda environment.

**Comment by manuelsmendoza** [comment]
it's worked! Thanks!
